name: Build and run tests on host OS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          compiler: g++-10

        - os: ubuntu-latest
          compiler: clang++-12

        - os: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install compilers
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt install gcc-10 g++-10 clang-12 libc++-12-dev libc++abi-12-dev

    - name: Configure CMake
      run: cmake lib/CMakeLists.txt -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -Dveridie_build_tests=ON -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -VV -C ${{env.BUILD_TYPE}}
